version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=Password111
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      - mediapatrik-network

networks:
  mediapatrik-network:
    name: 'mediapatrik-network'
