spring:
  messages:
    encoding: ISO-8859-1
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?schema=public
    username: mediapatrik
    password: Password111
    driver-class-name: org.postgresql.Driver
